name: Building DockerImage
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

    # - name: Build the Docker image
    #   run: docker build -t mydockerimage  -f  Dockerfile . 

      - name: Login into Dockerhub
        env:
         DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
         DOCKER_PASS: ${{secrets.DOCKERHUB_TOKEN }}
        run: | 
           docker login -u $DOCKER_USER -p $DOCKER_PASS 
     
      - name: Build the Docker image
        run: docker build -t mydockerimage  -f  Dockerfile . 

      - name: Push the Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sampledocker