name: This is second workflow
on: [push]
jobs: 
   firstJob: 
       runs-on: ubuntu-latest
       env: 
         hostname: DevOps
         app: githubaction 
       steps:
        - name: Checking the hostname 
          run: |
           sudo hostname
        - name: Set New hostname
          run: | 
            sudo hostnamectl set-hostname "$hostname
            hostname
        - name: Checking the Condition using Env
          if: ${{ env.app == 'githubaction' }}
          run: | 
            echo "True !"
             
           